In [142]:
import numpy as np
import pandas as pd
import numpy.random as npr
import numpy.linalg as npl
import random
import scipy.sparse.linalg as ssl

### Q1 Write a function that takes n, a1, a2 and s as inputs, and returns a sample  of length n, drawn from a uniform distribution U(a1,a2). The seed should be set to s.

In [174]:
def exercise1(n,a1,a2,s):
    np.random.seed(s)
    x = np.random.uniform(a1,a2,n)
    return x

In [175]:
exercise1(10,0,10,1)

array([  4.17022005e+00,   7.20324493e+00,   1.14374817e-03,
         3.02332573e+00,   1.46755891e+00,   9.23385948e-01,
         1.86260211e+00,   3.45560727e+00,   3.96767474e+00,
         5.38816734e+00])

# A multiple linear regression model is defined as
#### y =  b0 + b1*x1 + b2*x2 + b3*x3 + b4*x4 + ... + bpxp + epsilon
#### where p is the dimension and {x1,x2,...,xp} are the variables

#### To fit a linear regression model to a dataset we use the standard equation
#### b = (X^T X)^{-1} X^T y, to estimate the coefficients b = [b0, b1, ... , bp]. 
#### Here, y is the dataset (1D array) and X is a matrix where the first column is 
#### filled entirely with 1s and the subsequent columns are x1, x2, etc. 

### Q2 Write a function that takes p and a list S as inputs, and returns the matrix X. Use your function from exercise one to create the x1, x2, ... , xp variables, with n = 1000, a1 = 0 and a2 =10. The input S = (s0, s1, ... , sp),   where si corresponds to the seed that should be used to create the variable xi. Hint: Python treats all 1D arrays as row vectors. Instead Create the transpose of X and return its tranpose ((X^T)^T=X). Also, the function vstack will come in useful here. 

In [176]:
def exercise2(p,S):
    n = 1000
    a1 = 0
    a2 = 10
    X=np.ones((1,n))
    for i in range(1,p+1):
        i=exercise1(n,a1,a2,S[i-1])
        X=np.vstack((X,i))
    return X.transpose()

In [177]:
p = 4
S = [1,2,3,4]

exercise2(p,S)

array([[  1.00000000e+00,   4.17022005e+00,   4.35994902e+00,
          5.50797903e+00,   9.67029839e+00],
       [  1.00000000e+00,   7.20324493e+00,   2.59262318e-01,
          7.08147823e+00,   5.47232249e+00],
       [  1.00000000e+00,   1.14374817e-03,   5.49662478e+00,
          2.90904739e+00,   9.72684360e+00],
       ..., 
       [  1.00000000e+00,   6.68796606e+00,   6.80391484e+00,
          3.70698169e+00,   8.69198354e+00],
       [  1.00000000e+00,   3.25967207e+00,   8.53199812e+00,
          3.51653907e-01,   2.15144547e+00],
       [  1.00000000e+00,   7.74477266e+00,   7.92842528e+00,
          1.24693760e+00,   4.19331747e+00]])

### Q3 Write a function that takes the matirx X and vector y as input, and performs a multiple linear regression, using the standard equation b = (X^T X)^{-1} X^T y, by calculating the inverse of (X^T X) and multiplying the result by (X^T y). The function should return the vector b, which contains the fits for the intercept and slope parameters (b0, b1, b2, b3, b4)

In [181]:
y = npr.randn(5,1)
X = npr.randn(5,5)

def exercise3(X,y):
    XT=X.transpose()
    XTX=np.dot(XT,X)
    
    XTX_inv=npl.inv(XTX)
    XTy=np.dot(XT,y)
    b=np.dot(XTX_inv,XTy)
    return b

exercise3(X,y)

array([[-2.50937387],
       [-1.55489041],
       [-1.21802835],
       [-1.64080828],
       [-0.70053422]])

### Q4 Write another function, with the same inputs and outputs, which uses the solve function rather than finding the inverse and then multiplying.

In [179]:
def exercise4(X,y):
    XT=X.transpose()
    XTX=np.dot(XT,X)
    XTy=np.dot(XT,y)
    
    b=npl.solve(XTX,XTy)
    return b
    
print(exercise4(X,y))

[[-2.50937387]
 [-1.55489041]
 [-1.21802835]
 [-1.64080828]
 [-0.70053422]]


#### Try testing you functions for different models, e.g. y = 3 + 2*x1 - x2 + 0.5*x3 - 0.1*x4 + npr.normal(0,1,n) where x1, x2, x3, x4 should be comupted using the function exercise1, with  different seeds s1, s2, s3, s4. These seeds should be given as a list/array  into exercise2 to create the matrix X. Running exercise3 and exercise4 should  give the same result, a vector (1D array) of length p+1, with entries roughly  equal to the coefficients defined in your multiple linear model,  e.g. [3,2,-1,0.5,-0.1] for the above example. You can use %timeit to see  whether exercise3 or exercise4 is quicker for fitting the regression model.

In [180]:
s1 = 1
s2 = 2
s3 = 3
s4 = 4

y = 3 + 2*exercise1(1000,0,10,1) - exercise1(1000,0,10,2) + 0.5*exercise1(1000,0,10,3) - 0.1*exercise1(1000,0,10,4) + npr.normal(0,1,1000)

x = exercise2(p =4 , S = [1,2,3,4])

exercise3(x,y)

array([ 2.97205547,  1.99757688, -0.98359525,  0.484859  , -0.09242946])

In [168]:
%timeit exercise3(x,y)
%timeit exercise4(x,y)

31.5 µs ± 884 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
30.7 µs ± 614 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
