In [30]:
import numpy as np
import pandas as pd
import random

### Q1.  Write a function that takes n, a and b as inputs. The function should create a 1D array containing the numbers 0, 1, . . . , n−1 (n elements), multiple every element by a, add b to the 1st element and return the result

In [98]:
def exercise1(n,a,b):
    my_data = range(n)
    my_array = np.array(my_data)
    my_array = my_array*a
    my_array[0] = my_array[0] + b
    return my_array

In [99]:
exercise1(11,2,100)

array([100,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20])

### 2. Write a function that takes n, m, a, b and val as inputs. The function should create a n × m matrix (2D array) of zeros, set the entry [a, b] equal to val and return this matrix as its output

In [119]:
def exercise2(n,m,a,b,val):
    my_matrix = np.zeros((n,m))
    my_matrix[a,b] = val
    return my_matrix

In [120]:
exercise2(3,3,2,2,7)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  7.]])

### 3. Write a function that takes an array X, and the numbers a and b as inputs, and returns all of the values in X that at greater than a and less than b.

#### Firstly define a function rand_vector that returns a 2-D vector of dimension n*m filled with random integers between 0 and q to use for Q3


In [146]:
def rand_vector(q,n,m): 
    X = np.zeros((n,m))
    for j in range(0,m):
        for i in range (0,n):
            X[i,j] = random.randint(0,q)
    return X

In [161]:
X = rand_vector(100,5,5)
X

array([[ 44.,   7.,  94.,   4.,  70.],
       [ 23.,  71.,  42.,   8.,  44.],
       [ 57.,  83.,   2.,  86.,  12.],
       [ 57.,   0.,  30.,  73.,  39.],
       [ 14.,   1.,  98.,   5.,  20.]])

#### Now we definte the actual function and make use of the array X, we have generated

In [175]:
def exercise3(X,a,b):
    if a < b:
        return X[(X>a) & (X<b)]
    else:
        print("Please input an a less than b")

In [176]:
exercise3(X,10,30)

array([ 23.,  12.,  14.,  20.])

#### I made an alternative function which iterates through rows and columns for arrays of dimension ≤ 2

In [172]:
def alternative3(X,a,b):
    if a < b:
        if len(np.shape(X)) < 3:          
            for i in range(0,len(X)):
                for j in range(0,len(X[0])):
                    if a < X[i,j] < b:
                        print(X[i,j])
        else:
            print("Use first function, array has too many dimensions")
    else:
        print("Please input an a less than b")

In [173]:
alternative3(X,10,30)

23.0
12.0
14.0
20.0


### 4. Write a function that takes x as an input, converts x from degrees to radians and calculates sin of the x
#### This is a very useful function because the sine function in the numpy library requires the angle to be in radian format

In [110]:
def exercise4(x):
    q = np.radians(x)
    y = np.sin(q)
    print(x,"degrees in rads is",q,"and the sine of the angle is",y)

In [111]:
exercise4(180)

180 degrees in rads is 3.14159265359 and the sine of the angle is 1.22464679915e-16
